name: college_connect
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/regular.ttf

    - family: semiBold
      fonts:
        - asset: assets/fonts/semiBold.ttf

    - family: bold
      fonts:
        - asset: assets/fonts/bold.ttf
    - family: light
      fonts:
        - asset: assets/fonts/light.ttf